version: '3.4'

services:
  # api:
  #   container_name: dinkilink_api
  #   build:
  #     context: .
  #     dockerfile: ./backend/docker/app/Dockerfile
  #   ports:
  #     - '8080:8080'

  db:
    container_name: dinkilink_db
    image: postgres
    restart: always
    env_file:
      - ./backend/docker/db/.env
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./backend/docker/db/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh:ro

volumes:
  db-data:
