version: "3.5"

services:
  api:
    container_name: dinkilink_api
    image: donan/dinkilink_api:latest
    restart: always
    ports:
      - "80:80"
    depends_on:
      - db
    env_file:
      - ./db/.env

  db:
    container_name: dinkilink_db
    image: postgres:13
    restart: always
    env_file:
      - ./db/.env
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh:ro

volumes:
  db-data:
