version: "3.4"

services:
  # app:
  #   container_name: dinkilink_app
  #   build:
  #     context: ./app
  #     dockerfile: Dockerfile
  #   ports:
  #     - '3100:3000'
  #   volumes:
  #     - ./app:/dinkilink/app
  #     - /dinkilink/app/node_modules
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true
  #   stdin_open: true

  # app:
  #   container_name: dinkilink_app
  #   build:
  #     context: ./app
  #     dockerfile: Dockerfile
  #   environment:
  #     - NGINX_HOST=dinki.link
  #     - NGINX_PORT=80
  #   ports:
  #     - "80:80"

  api:
    container_name: dinkilink_api
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "40000:40000"
      - "8000:80"
    depends_on:
      - db
    volumes:
      - ./api:/dinkilink/app/src
    env_file:
      - ./db/.env

  db:
    container_name: dinkilink_db
    image: postgres:13
    restart: always
    env_file:
      - ./db/.env
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh:ro

volumes:
  db-data:
