version: '3.4'

services:
  app:
    container_name: dinkilink_app
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - '3100:3000'
    volumes:
      - ./app:/dinkilink/app
      - /dinkilink/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true

  api:
    container_name: dinkilink_api
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
      - '40000:40000'
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./api:/dinkilink/app/src
    env_file:
      - ./db/.env

  db:
    container_name: dinkilink_db
    image: postgres
    restart: always
    env_file:
      - ./db/.env
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh:ro
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U dinkilink']
      interval: 1s
      timeout: 5s
      retries: 10

volumes:
  db-data:
