version: "3.5"

services:
  # app:
  #   container_name: dinkilink_app
  #   build:
  #     context: ./app
  #     dockerfile: Dockerfile
  #   ports:
  #     - '3100:3000'
  #   volumes:
  #     - ./app:/dinkilink/app
  #     - /dinkilink/app/node_modules
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true
  #   stdin_open: true

  api:
    container_name: dinkilink_api
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
      - "888:80"
      - "40000:40000"
    depends_on:
      - db
    env_file:
      - ./db/.env

  db:
    container_name: dinkilink_db
    image: postgres:13
    restart: always
    env_file:
      - ./db/.env
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh:ro

volumes:
  db-data:
