version: '3.4'

services:
  api:
    container_name: dinkilink_app
    build:
      context: .
      dockerfile: ./api/docker/app/Dockerfile
    ports:
      - '8080:8080'

  db:
    container_name: dinkilink_db
    image: postgres
    restart: always
    env_file:
      - ./api/docker/db/.env
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./api/docker/db/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh:ro

volumes:
  db-data:
