version: "3.5"

services:
  api:
    container_name: dinkilink_api
    image: donan/dinkilink_api:latest
    restart: always
    depends_on:
      - db
    env_file:
      - ./db/.env
    networks:
      - default
      - web
    expose:
      - "9000"
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.protocol=http"
      - "traefik.http.routers.dinkilink.rule=Host(`dinki.link`)"
      - "traefik.http.routers.dinkilink.entrypoints=web"
      - "traefik.http.routers.dinkilink.entrypoints=websecure"
      - "traefik.http.routers.dinkilink.tls.certresolver=dinkilinkhttpchallenge"
      - "traefik.http.routers.wwwdinkilink.rule=Host(`www.dinki.link`)"
      - "traefik.http.routers.wwwdinkilink.entrypoints=web"
      - "traefik.http.routers.wwwdinkilink.entrypoints=websecure"
      - "traefik.http.routers.wwwdinkilink.tls.certresolver=dinkilinkhttpchallenge"

  db:
    container_name: dinkilink_db
    image: postgres:13
    restart: always
    env_file:
      - ./db/.env
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh:ro
    networks:
      - default

volumes:
  db-data:

networks:
  web:
    external: true
