#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER $POSTGRES_API_USER
    WITH PASSWORD '$POSTGRES_API_PASSWORD';

    GRANT ALL PRIVILEGES ON DATABASE dinkilink TO $POSTGRES_API_USER;
EOSQL