FROM golang:1.14-alpine as build-env

WORKDIR /dinkilink/api/src

RUN apk update && apk add --no-cache gcc musl-dev git bash

COPY ./go.mod ./go.sum ./

RUN go mod download

COPY . ./api/src

RUN go build -ldflags '-w -s' -a -o ./bin/api ./cmd/api

FROM alpine
RUN apk update && apk add --no-cache bash

COPY --from=build-env /dinkilink/bin/api /dinkilink/api

EXPOSE 8080

CMD ["/dinkilink/api"]