FROM golang:1.14-alpine 

WORKDIR /dinkilink/app/src

RUN apk update && apk add --no-cache gcc musl-dev git bash

COPY . .

RUN go mod download

RUN go get github.com/githubnemo/CompileDaemon

EXPOSE 8080 40000 8000

CMD CompileDaemon \
    --build="go build -gcflags=`all=-N -l` -ldflags=`-w -s` -a -o ../bin ./cmd/app" \ 
    --command="../bin"
