FROM golang:1.14-alpine 

WORKDIR /api

RUN apk update && apk add --no-cache gcc musl-dev git bash

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN go get github.com/githubnemo/CompileDaemon
RUN go get github.com/go-delve/delve/cmd/dlv

EXPOSE 8080 40000 8000

CMD CompileDaemon \
    --build="go build -gcflags=`all=-N -l` -ldflags=`-w -s` -a -o ./bin ./cmd/app" \ 
    --command="dlv --listen=:40000 --headless=true --api-version=2 --accept-multiclient exec ./bin"
